#!/usr/bin/env python
"""
Demo: Create GitHub PR for a specific code fix

This demonstrates PR creation by directly specifying:
- The file to fix (USBMediaHandler.cpp)
- The issue description
- The recommended fix

This bypasses full RCA analysis and goes straight to PR creation.
"""

import os
import sys

# Add src to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from src.rca_infotainment.git_service import GitService
from src.utils.config import load_config

try:
    from dotenv import load_dotenv
    load_dotenv()
except:
    pass


def main():
    print("\n" + "="*70)
    print("  GITHUB PR CREATION DEMO")
    print("="*70)
    print()
    
    # Load config
    config = load_config('config/config.yaml')
    
    # Initialize Git service
    print("Initializing Git service...")
    git_config = config.get('integrations', {}).get('git', {})
    git_service = GitService(git_config)
    
    if not git_service.is_connected():
        print("✗ Git not connected!")
        print("  Check GIT_REPO_URL and GIT_TOKEN in .env")
        return
    
    print(f"✓ Git connected: {git_service.repo_url}")
    print()
    
    # Define the fix
    defect_id = "KAN-16"
    fix_title = "[KAN-16] Fix USB source switch delay - Optimize MediaService initialization"
    fix_description = """
## Root Cause Analysis
**Issue**: USB source switch takes 378ms instead of target <200ms

**Root Cause**: MediaService initialization during source switch includes unnecessary delays:
- Redundant device enumeration
- Sequential initialization instead of parallel
- Excessive logging during critical path

## Proposed Fix
Optimize the source switch flow in USBMediaHandler.cpp:
1. Cache device enumeration results
2. Parallelize USB device initialization  
3. Reduce logging verbosity during STR measurement
4. Use async I/O for file system operations

## Expected Impact
- Reduce source switch time from 378ms to ~150ms
- Improve user experience for media source switching
- Meet STR KPI requirements (<200ms)

---
*This PR was automatically generated by RCA Agent based on defect KAN-16*
"""
    
    branch_name = f"fix/kan-16-usb-source-switch-delay"
    
    print("Creating PR...")
    print(f"  Branch: {branch_name}")
    print(f"  Title: {fix_title}")
    print()
    
    try:
        # Create PR
        result = git_service.create_pull_request(
            defect_id=defect_id,
            branch_name=branch_name,
            title=fix_title,
            description=fix_description,
            base_branch="main"
        )
        
        if result.get('success'):
            pr = result.get('pr', {})
            print("="*70)
            print("✓ PULL REQUEST CREATED SUCCESSFULLY!")
            print("="*70)
            print()
            print(f"  PR Number: #{pr.get('number', 'N/A')}")
            print(f"  Title: {pr.get('title', 'N/A')}")
            print(f"  URL: {pr.get('url', 'N/A')}")
            print(f"  State: {pr.get('state', 'N/A')}")
            print()
            print(f"View the PR: {pr.get('url', 'N/A')}")
            print()
            
            # Open in browser
            import webbrowser
            if pr.get('url'):
                webbrowser.open(pr['url'])
                
        else:
            print("✗ Failed to create PR")
            print(f"  Result: {result}")
            errors = result.get('errors', []) if result else []
            if errors:
                for error in errors:
                    print(f"  Error: {error}")
            else:
                print("  No error details returned - check logs")
                print()
                print("You can create the PR manually at:")
                print(f"  https://github.com/RavindraTabde10/dummy_ivi_sw_repo/pull/new/fix/kan-16-usb-source-switch-delay")
            
    except Exception as e:
        print(f"✗ Error: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
